%{!?perl_vendorlib: %define perl_vendorlib %(eval "`%{__perl} -V:installvendorlib`"; echo $installvendorlib)}

Name:           perl-Layout-Manager
Version:        0.35
Release:        1%{?dist}
Summary:        Layout::Manager Perl module
License:        GPL+ or Artistic
Group:          Development/Libraries
URL:            http://search.cpan.org/dist/Layout-Manager/
Source0:        Layout-Manager-%{version}.tar.gz 
BuildRoot:      %{_tmppath}/%{name}-%{version}-%{release}-root-%(%{__id_u} -n)
BuildArch:      noarch
BuildRequires:  perl(ExtUtils::MakeMaker)
BuildRequires:  perl(Geometry::Primitive) >= 0.16
BuildRequires:  perl(Graphics::Primitive) >= 0.43
BuildRequires:  perl(Moose) >= 0.79
BuildRequires:  perl(Test::More)
Requires:       perl(Geometry::Primitive) >= 0.16
Requires:       perl(Graphics::Primitive) >= 0.43
Requires:       perl(Moose) >= 0.79

Provides:       perl(Layout::Manager)
Provides:       perl(Layout::Manager::Absolute)
Provides:       perl(Layout::Manager::Axis)
Provides:       perl(Layout::Manager::Compass)
Provides:       perl(Layout::Manager::Flow)
Provides:       perl(Layout::Manager::Grid)
Provides:       perl(Layout::Manager::Single)

%description
perl Makefile.PL make make test make install

%prep
%setup -q -n Layout-Manager-%{version}

%build
%{__perl} Makefile.PL INSTALLDIRS=vendor
make %{?_smp_mflags}

%install
rm -rf %{buildroot}

make pure_install PERL_INSTALL_ROOT=%{buildroot}

find %{buildroot} -type f -name .packlist -exec rm -f {} \;
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null \;

%{_fixperms} %{buildroot}/*

%check || :
make test

%clean
rm -rf %{buildroot}

%files
%defattr(-,root,root,-)
%doc Changes README
%{perl_vendorlib}/*
%{_mandir}/man3/*

%changelog
* Fri Apr 05 2024 Otto J Wittner <otto.wittner@sikt.no> 0.35-1
- Specfile autogenerated by cpanspec 1.78.
