%{!?perl_vendorlib: %define perl_vendorlib %(eval "`%{__perl} -V:installvendorlib`"; echo $installvendorlib)}

Name:           perl-MooseX-Storage
Version:        0.53
Release:        1%{?dist}
Summary:        Serialization framework for Moose classes
License:        GPL+ or Artistic
Group:          Development/Libraries
URL:            http://search.cpan.org/dist/MooseX-Storage/
Source0:        MooseX-Storage-%{version}.tar.gz 
BuildRoot:      %{_tmppath}/%{name}-%{version}-%{release}-root-%(%{__id_u} -n)
BuildArch:      noarch
BuildRequires:  perl >= 0:5.008
BuildRequires:  perl(Carp)
BuildRequires:  perl(Data::Dumper)
BuildRequires:  perl(Digest)
BuildRequires:  perl(ExtUtils::MakeMaker)
BuildRequires:  perl(File::Spec)
BuildRequires:  perl(File::Spec::Functions)
BuildRequires:  perl(File::Temp)
BuildRequires:  perl(IO::AtomicFile)
BuildRequires:  perl(IO::File)
BuildRequires:  perl(JSON::MaybeXS) >= 1.001000
BuildRequires:  perl(JSON::PP)
BuildRequires:  perl(Module::Runtime)
BuildRequires:  perl(Moose) >= 0.99
BuildRequires:  perl(Moose::Meta::Attribute)
BuildRequires:  perl(Moose::Role)
BuildRequires:  perl(Moose::Util::TypeConstraints)
BuildRequires:  perl(Scalar::Util)
BuildRequires:  perl(Storable)
BuildRequires:  perl(String::RewritePrefix)
BuildRequires:  perl(Test::Deep)
BuildRequires:  perl(Test::Deep::Type)
BuildRequires:  perl(Test::Fatal)
BuildRequires:  perl(Test::More) >= 0.88
BuildRequires:  perl(Test::Needs)
BuildRequires:  perl(YAML)
BuildRequires:  perl(YAML::Any)
BuildRequires:  perl(YAML::Syck)
BuildRequires:  perl(YAML::XS)
BuildRequires:  perl(namespace::autoclean)
BuildRequires:  perl(open)
BuildRequires:  perl(overload)
BuildRequires:  perl(strict)
BuildRequires:  perl(utf8)
BuildRequires:  perl(warnings)
Requires:       perl(Carp)
Requires:       perl(Data::Dumper)
Requires:       perl(Digest)
Requires:       perl(IO::AtomicFile)
Requires:       perl(IO::File)
Requires:       perl(JSON::MaybeXS) >= 1.001000
Requires:       perl(Module::Runtime)
Requires:       perl(Moose) >= 0.99
Requires:       perl(Moose::Meta::Attribute)
Requires:       perl(Moose::Role)
Requires:       perl(Scalar::Util)
Requires:       perl(Storable)
Requires:       perl(String::RewritePrefix)
Requires:       perl(YAML)
Requires:       perl(YAML::Any)
Requires:       perl(YAML::Syck)
Requires:       perl(YAML::XS)
Requires:       perl(namespace::autoclean)

Provides:       perl(MooseX::Storage)

%description
MooseX::Storage is a serialization framework for Moose, it provides a very
flexible and highly pluggable way to serialize Moose classes to a number of
different formats and styles.

%prep
%setup -q -n MooseX-Storage-%{version}

%build
%{__perl} Makefile.PL INSTALLDIRS=vendor
make %{?_smp_mflags}

%install
rm -rf %{buildroot}

make pure_install PERL_INSTALL_ROOT=%{buildroot}

find %{buildroot} -type f -name .packlist -exec rm -f {} \;
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null \;

%{_fixperms} %{buildroot}/*

%check || :
make test

%clean
rm -rf %{buildroot}

%files
%defattr(-,root,root,-)
%doc CONTRIBUTING Changes LICENSE META.json README dist.ini
%{perl_vendorlib}/*
%{_mandir}/man3/*

%changelog
* Thu Apr 04 2024 Otto J Wittner <otto.wittner@sikt.no> 0.53-1
- Specfile autogenerated by cpanspec 1.78.
