filter {
    # Parse incoming message as json (ref 02-pscheduler_common.conf)
    if [message] {
        ruby {
            path => "/usr/lib/perfsonar/logstash/ruby/pscheduler_proxy_normalize.rb"
        }
    }

    if [test][type] == "trace" {
       if [run][result-full] {
         # Create cloned event
         clone {
	   clones => ["raw-packets-clone"]
	 }
       }
    }
}
filter {
    if [type] == "raw-packets-clone" {
       # Clean up type-field and "save" raw-packets (by moving them out of result structure)
       mutate {
         remove_field => ["type"]
         rename => {
                "[run][result-full]" => "[raw-trace]"
         }
       }
    }
}