filter {
    if [test][type] == "trace" {
        if [raw-packets] {
            # Prefix test-type with "raw" tag
	    # (to ensure raw data is stored in separate index)
            mutate {
	        update => ["[test][type]", "raw_%{[test][type]}"]
	    }
	    # Move raw-data back into result-structure again
	    mutate {
                rename => {
                    "[raw-trace]" => "[result-full]"
                }
            }
	}
    }
}
