filter {
    if [event_type] {
       # Add some tags based on event types
       if 'gap-ana' not in [tags] {
       	   # Check if current dataset is still gap-ana data
	   if [ana_tool] and [ana_tool] == "gap-ana" {
	      	mutate { add_tag => "gap-ana" }
	   }
       }
       if 'trace-ana' not in [tags] {
       	   # Check if current dataset is still trace-ana data
	   if [ana_tool] and [ana_tool] == "trace-ana" {
	      	mutate { add_tag => "trace-ana" }
	   }
       }
    }
}