LICENSE usr/lib/perfsonar/microdep-map/
microdep-map/* usr/lib/perfsonar/microdep-map/ 
bin/microdep_commands/elastic-get-date-type.pl usr/lib/perfsonar/bin/microdep_commands/
bin/microdep_commands/microdep-config.cgi usr/lib/perfsonar/bin/microdep_commands/
bin/microdep_commands/yaml-to-json.cgi usr/lib/perfsonar/bin/microdep_commands/
bin/microdep_commands/get-mapconfig.cgi usr/lib/perfsonar/bin/microdep_commands/
bin/microdep_commands/microdep-psconfig-load.pl usr/lib/perfsonar/bin/microdep_commands/
bin/microdep_commands/json2table.pl usr/lib/perfsonar/bin/microdep_commands/
bin/microdep_commands/rabbitmq-consume.py usr/lib/perfsonar/bin/microdep_commands/
etc/mapconfig.yml etc/perfsonar/microdep/
etc/mapconfig.d/* etc/perfsonar/microdep/mapconfig.d/
etc/microdep-config.yml etc/perfsonar/microdep/
etc/microdep.db etc/perfsonar/microdep/mp-dragonlab/etc/
etc/apache-microdep-map.conf etc/apache2/conf-available/
scripts/perfsonar-microdep-watchconfig.path lib/systemd/system
scripts/perfsonar-microdep-watchconfig.service lib/systemd/system


