etc/logstash/microdep/* usr/lib/perfsonar/logstash/microdep_pipeline/
etc/logstash/microdep-pipelines.yml etc/perfsonar/microdep/logstash/
etc/os-template-gap-ana.json etc/perfsonar/microdep/
etc/os-template-trace-ana.json etc/perfsonar/microdep/
etc/microdep-tests.json.example etc/perfsonar/microdep/
etc/microdep-tests-packet-subcount.json.example etc/perfsonar/microdep/
etc/psconfig/archives.d/* etc/pscheduler/default-archives/
bin/microdep_commands/qstream-gap-ana usr/lib/perfsonar/bin/microdep_commands/
bin/microdep_commands/trace_event_reader.py usr/lib/perfsonar/bin/microdep_commands/ 
bin/microdep_commands/create_new_db.sh usr/lib/perfsonar/bin/microdep_commands/
scripts/perfsonar-microdep-gap-ana.service lib/systemd/system/
scripts/perfsonar-microdep-trace-ana.service lib/systemd/system/
scripts/perfsonar-microdep-restart.service lib/systemd/system/
scripts/perfsonar-microdep-restart.timer lib/systemd/system/
etc/logrotate.d/microdep /etc/logrotate.d/

