#
# Based on https://github.com/jc21/docker-rpmbuild-centos7/blob/master/docker/Dockerfile
#
# 2024-02-02 Otto J Wittner
#

FROM almalinux:9
MAINTAINER Otto J Wittner - Sikt

RUN dnf update -y && dnf install -y yum-utils && dnf config-manager --set-enabled crb &&  dnf install -y epel-release procps-ng rpm-build sudo rpmdevtools make nano

# Add stuff requried to build rpm packages of pip-installable python modules
RUN dnf install -y python3-devel git python3-sphinx python3-setuptools gcc python3-docutils
RUN python3 -m pip install pyp2rpm
RUN python3 -m pip install sphinxcontrib.towncrier
#RUN python3 -m pip install pypi2rpm
#RUN python3 -m pip install py2pack

# build files
COPY bin/build-spec /bin/
COPY bin/build-all /bin/

# Sudo
COPY etc/sudoers.d/wheel /etc/sudoers.d/
RUN chown root:root /etc/sudoers.d/*

# Remove requiretty from sudoers main file
RUN sed -i '/Defaults    requiretty/c\#Defaults    requiretty' /etc/sudoers

# Rpm User
RUN adduser -G wheel rpmbuilder
#RUN mkdir -p /home/rpmbuilder/rpmbuild/{BUILD,SPECS,SOURCES,BUILDROOT,RPMS,SRPMS,tmp}
RUN mkdir -p /home/rpmbuilder/rpmbuild/{BUILD,BUILDROOT,tmp}
RUN chmod -R 777 /home/rpmbuilder/rpmbuild

COPY .rpmmacros /home/rpmbuilder/
USER rpmbuilder

WORKDIR /home/rpmbuilder
