%{!?perl_vendorlib: %define perl_vendorlib %(eval "`%{__perl} -V:installvendorlib`"; echo $installvendorlib)}

Name:           perl-Graphics-Primitive
Version:        0.67
Release:        1%{?dist}
Summary:        Device and library agnostic graphic primitives
License:        GPL+ or Artistic
Group:          Development/Libraries
URL:            http://search.cpan.org/dist/Graphics-Primitive/
Source0:        Graphics-Primitive-%{version}.tar.gz 
BuildRoot:      %{_tmppath}/%{name}-%{version}-%{release}-root-%(%{__id_u} -n)
BuildArch:      noarch
BuildRequires:  perl(Data::Visitor::Callback) >= 0.30
BuildRequires:  perl(ExtUtils::MakeMaker)
BuildRequires:  perl(Forest) >= 0.06
BuildRequires:  perl(Geometry::Primitive) >= 0.16
BuildRequires:  perl(Graphics::Color) >= 0.20
BuildRequires:  perl(JSON::Any) >= 1.22
BuildRequires:  perl(Moose) >= 0.90
BuildRequires:  perl(MooseX::Clone) >= 0.04
BuildRequires:  perl(MooseX::Storage) >= 0.17
BuildRequires:  perl(Test::More)
Requires:       perl(Data::Visitor::Callback) >= 0.30
Requires:       perl(Forest) >= 0.06
Requires:       perl(Geometry::Primitive) >= 0.16
Requires:       perl(Graphics::Color) >= 0.20
Requires:       perl(JSON::Any) >= 1.22
Requires:       perl(Moose) >= 0.90
Requires:       perl(MooseX::Clone) >= 0.04
Requires:       perl(MooseX::Storage) >= 0.17

Provides:       perl(Graphics::Primitive)
Provides:       perl(Graphics::Primitive::Aligned)
Provides:       perl(Graphics::Primitive::Border)
Provides:       perl(Graphics::Primitive::Brush)
Provides:       perl(Graphics::Primitive::Canvas)
Provides:       perl(Graphics::Primitive::Component)
Provides:       perl(Graphics::Primitive::ComponentList)
Provides:       perl(Graphics::Primitive::Container)
Provides:       perl(Graphics::Primitive::Driver)
Provides:       perl(Graphics::Primitive::Font)
Provides:       perl(Graphics::Primitive::Image)
Provides:       perl(Graphics::Primitive::Insets)
Provides:       perl(Graphics::Primitive::Operation)
Provides:       perl(Graphics::Primitive::Oriented)
Provides:       perl(Graphics::Primitive::Paint)
Provides:       perl(Graphics::Primitive::Path)
Provides:       perl(Graphics::Primitive::TextBox)
Provides:       perl(Graphics::Primitive::Paint::Gradient)
Provides:       perl(Graphics::Primitive::Paint::Solid)
Provides:       perl(Graphics::Primitive::Paint::Gradient::Linear)
Provides:       perl(Graphics::Primitive::Paint::Gradient::Radial)
Provides:       perl(Graphics::Primitive::Operation::Fill)
Provides:       perl(Graphics::Primitive::Operation::Stroke)
Provides:       perl(Graphics::Primitive::Driver::TextLayout)

%description
Graphics::Primitive is library agnostic system for drawing things.

%prep
%setup -q -n Graphics-Primitive-%{version}

%build
%{__perl} Makefile.PL INSTALLDIRS=vendor
make %{?_smp_mflags}

%install
rm -rf %{buildroot}

make pure_install PERL_INSTALL_ROOT=%{buildroot}

find %{buildroot} -type f -name .packlist -exec rm -f {} \;
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null \;

%{_fixperms} %{buildroot}/*

%check || :
make test

%clean
rm -rf %{buildroot}

%files
%defattr(-,root,root,-)
%doc Changes README
%{perl_vendorlib}/*
%{_mandir}/man3/*

%changelog
* Fri Apr 05 2024 Otto J Wittner <otto.wittner@sikt.no> 0.67-1
- Specfile autogenerated by cpanspec 1.78.
