%{!?perl_vendorlib: %define perl_vendorlib %(eval "`%{__perl} -V:installvendorlib`"; echo $installvendorlib)}

Name:           perl-Text-Flow
Version:        0.01
Release:        1%{?dist}
Summary:        Flexible text flowing and word wrapping for not just ASCII output
License:        GPL+ or Artistic
Group:          Development/Libraries
URL:            http://search.cpan.org/dist/Text-Flow/
Source0:        Text-Flow-%{version}.tar.gz 
BuildRoot:      %{_tmppath}/%{name}-%{version}-%{release}-root-%(%{__id_u} -n)
BuildArch:      noarch
BuildRequires:  perl(List::Util)
BuildRequires:  perl(Module::Build)
BuildRequires:  perl(Moose) >= 0.21
BuildRequires:  perl(Test::Exception) >= 0.21
BuildRequires:  perl(Test::LongString)
BuildRequires:  perl(Test::More) >= 0.62
Requires:       perl(Moose) >= 0.21

Provides:       perl(Text::Flow::Wrap)
Provides:       perl(Text::Flow)

%description
This module provides a flexible way to wrap and flow text for both ASCII
and non-ASCII outputs.

%prep
%setup -q -n Text-Flow-%{version}

%build
%{__perl} Build.PL --installdirs=vendor
./Build

%install
rm -rf %{buildroot}

./Build install --destdir=%{buildroot} --create_packlist=0
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null \;

%{_fixperms} %{buildroot}/*

%check || :
./Build test

%clean
rm -rf %{buildroot}

%files
%defattr(-,root,root,-)
%doc Changes README
%{perl_vendorlib}/*
%{_mandir}/man3/*

%changelog
* Fri Apr 05 2024 Otto J Wittner <otto.wittner@sikt.no> 0.01-1
- Specfile autogenerated by cpanspec 1.78.
