%{!?perl_vendorlib: %define perl_vendorlib %(eval "`%{__perl} -V:installvendorlib`"; echo $installvendorlib)}

Name:           perl-Color-Scheme
Version:        1.08
Release:        1%{?dist}
Summary:        Generate pleasant color schemes
License:        GPL+ or Artistic
Group:          Development/Libraries
URL:            http://search.cpan.org/dist/Color-Scheme/
Source0:        Color-Scheme-%{version}.tar.gz 
BuildRoot:      %{_tmppath}/%{name}-%{version}-%{release}-root-%(%{__id_u} -n)
BuildArch:      noarch
BuildRequires:  perl >= 0:5.012
BuildRequires:  perl(Carp)
BuildRequires:  perl(Exporter)
BuildRequires:  perl(ExtUtils::MakeMaker)
BuildRequires:  perl(File::Spec)
BuildRequires:  perl(List::Util) >= 1.14
BuildRequires:  perl(POSIX) >= 1.08
BuildRequires:  perl(Test::More) >= 0.96
BuildRequires:  perl(parent)
BuildRequires:  perl(strict)
BuildRequires:  perl(warnings)
Requires:       perl(Carp)
Requires:       perl(List::Util) >= 1.14
Requires:       perl(POSIX) >= 1.08
Requires:       perl(strict)
Requires:       perl(warnings)

Provides:       perl(Color::Scheme)

%description
This module is a Perl implementation of Color Schemes 2
(http://wellstyled.com/tools/colorscheme2/), a color scheme generator.
Start by visiting the Color Schemes 2 web site and playing with the colors.
When you want to generate those schemes on the fly, begin using this
module. The descriptions herein don't make too much sense without actually
seeing the colorful results.

%prep
%setup -q -n Color-Scheme-%{version}

%build
%{__perl} Makefile.PL INSTALLDIRS=vendor
make %{?_smp_mflags}

%install
rm -rf %{buildroot}

make pure_install PERL_INSTALL_ROOT=%{buildroot}

find %{buildroot} -type f -name .packlist -exec rm -f {} \;
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null \;

%{_fixperms} %{buildroot}/*

%check || :
make test

%clean
rm -rf %{buildroot}

%files
%defattr(-,root,root,-)
%doc Changes LICENSE META.json README dist.ini
%{perl_vendorlib}/*
%{_mandir}/man3/*

%changelog
* Thu Apr 04 2024 Otto J Wittner <otto.wittner@sikt.no> 1.08-1
- Specfile autogenerated by cpanspec 1.78.
