%{!?perl_vendorlib: %define perl_vendorlib %(eval "`%{__perl} -V:installvendorlib`"; echo $installvendorlib)}

Name:           perl-AnyEvent-RabbitMQ
Version:        1.22
Release:        1%{?dist}
Summary:        Asynchronous and multi channel Perl AMQP client
License:        GPL+ or Artistic
Group:          Development/Libraries
URL:            http://search.cpan.org/dist/AnyEvent-RabbitMQ/
Source0:        AnyEvent-RabbitMQ-%{version}.tar.gz
BuildRoot:      %{_tmppath}/%{name}-%{version}-%{release}-root-%(%{__id_u} -n)
BuildArch:      noarch
BuildRequires:  perl >= 0:5.010
BuildRequires:  perl(AnyEvent)
BuildRequires:  perl(Devel::GlobalDestruction)
BuildRequires:  perl(ExtUtils::MakeMaker)
BuildRequires:  perl(File::ShareDir)
BuildRequires:  perl(List::MoreUtils)
BuildRequires:  perl(Net::AMQP) >= 0.06
#BuildRequires:  perl-Net-AMQP >= 0.06
BuildRequires:  perl(Readonly) >= 1.03
BuildRequires:  perl(Test::Exception)
BuildRequires:  perl(Test::More)
BuildRequires:  perl(namespace::clean)
BuildRequires:  perl(version) >= 0.77
BuildRequires:  perl(File::ShareDir::Install)
Requires:       perl(AnyEvent)
Requires:       perl(Devel::GlobalDestruction)
Requires:       perl(File::ShareDir)
Requires:       perl(List::MoreUtils)
Requires:       perl(Net::AMQP) >= 0.06
#Requires:       perl-Net-AMQP >= 0.06
Requires:       perl(Readonly) >= 1.03
Requires:       perl(namespace::clean)

Provides:       perl(AnyEvent::RabbitMQ)

%description
AnyEvent::RabbitMQ is an AMQP(Advanced Message Queuing Protocol) client
library, that is intended to allow you to interact with AMQP-compliant
message brokers/servers such as RabbitMQ in an asynchronous fashion.

%prep
%setup -q -n AnyEvent-RabbitMQ-%{version}

%build
%{__perl} Makefile.PL INSTALLDIRS=vendor
make %{?_smp_mflags}

%install
rm -rf %{buildroot}

make pure_install PERL_INSTALL_ROOT=%{buildroot}

find %{buildroot} -type f -name .packlist -exec rm -f {} \;
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null \;

%{_fixperms} %{buildroot}/*

%check || :
make test

%clean
rm -rf %{buildroot}

%files
%defattr(-,root,root,-)
%doc Changes LICENSE META.json README cpanfile dist.ini perlcritic.rc
%{perl_vendorlib}/*
%{_mandir}/man3/*

%changelog
* Wed Apr 03 2024 Otto J Wittner <otto.wittner@sikt.no> 1.22-1
- Specfile autogenerated by cpanspec 1.78.
