%{!?perl_vendorlib: %define perl_vendorlib %(eval "`%{__perl} -V:installvendorlib`"; echo $installvendorlib)}

Name:           perl-Test-Deep-Type
Version:        0.008
Release:        1%{?dist}
Summary:        Test::Deep plugin for validating type constraints
License:        GPL+ or Artistic
Group:          Development/Libraries
URL:            http://search.cpan.org/dist/Test-Deep-Type/
Source0:        Test-Deep-Type-%{version}.tar.gz 
BuildRoot:      %{_tmppath}/%{name}-%{version}-%{release}-root-%(%{__id_u} -n)
BuildArch:      noarch
BuildRequires:  perl >= 0:5.006
BuildRequires:  perl(Exporter) >= 5.57
BuildRequires:  perl(ExtUtils::MakeMaker)
BuildRequires:  perl(File::Spec)
BuildRequires:  perl(Scalar::Util)
BuildRequires:  perl(Test::Deep)
BuildRequires:  perl(Test::Deep::Cmp)
BuildRequires:  perl(Test::Fatal)
BuildRequires:  perl(Test::More) >= 0.88
BuildRequires:  perl(Test::Needs)
BuildRequires:  perl(Test::Tester) >= 0.108
BuildRequires:  perl(Try::Tiny)
BuildRequires:  perl(if)
BuildRequires:  perl(overload)
BuildRequires:  perl(parent)
BuildRequires:  perl(strict)
BuildRequires:  perl(warnings)
Requires:       perl(Exporter) >= 5.57
Requires:       perl(Scalar::Util)
Requires:       perl(Test::Deep::Cmp)
Requires:       perl(Try::Tiny)
Requires:       perl(parent)
Requires:       perl(strict)
Requires:       perl(warnings)

Provides:       perl(Test::Deep::Type)

%description
This is a Test::Deep plugin that provides the sub is_type to indicate that
the data being tested must validate against the passed type. This is an
actual type object, not a string name -- for example something provided via
MooseX::Types, or a plain old coderef that returns a bool (such as what
might be used in a Moo type constraint).

%prep
%setup -q -n Test-Deep-Type-%{version}

%build
%{__perl} Makefile.PL INSTALLDIRS=vendor
make %{?_smp_mflags}

%install
rm -rf %{buildroot}

make pure_install PERL_INSTALL_ROOT=%{buildroot}

find %{buildroot} -type f -name .packlist -exec rm -f {} \;
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null \;

%{_fixperms} %{buildroot}/*

%check || :
make test

%clean
rm -rf %{buildroot}

%files
%defattr(-,root,root,-)
%doc CONTRIBUTING Changes LICENCE META.json README dist.ini
%{perl_vendorlib}/*
%{_mandir}/man3/*

%changelog
* Fri Apr 05 2024 Otto J Wittner <otto.wittner@sikt.no> 0.008-1
- Specfile autogenerated by cpanspec 1.78.
