%{!?perl_vendorlib: %define perl_vendorlib %(eval "`%{__perl} -V:installvendorlib`"; echo $installvendorlib)}

Name:           perl-String-RewritePrefix
Version:        0.009
Release:        1%{?dist}
Summary:        String::RewritePrefix Perl module
License:        GPL+ or Artistic
Group:          Development/Libraries
URL:            http://search.cpan.org/dist/String-RewritePrefix/
Source0:        String-RewritePrefix-%{version}.tar.gz 
BuildRoot:      %{_tmppath}/%{name}-%{version}-%{release}-root-%(%{__id_u} -n)
BuildArch:      noarch
BuildRequires:  perl >= 0:5.012
BuildRequires:  perl(Carp)
BuildRequires:  perl(ExtUtils::MakeMaker)
BuildRequires:  perl(File::Spec)
BuildRequires:  perl(Sub::Exporter) >= 0.972
BuildRequires:  perl(Test::More) >= 0.96
BuildRequires:  perl(strict)
BuildRequires:  perl(warnings)
Requires:       perl(Carp)
Requires:       perl(Sub::Exporter) >= 0.972
Requires:       perl(strict)
Requires:       perl(warnings)

Provides:       perl(String::RewritePrefix)

%description
String::RewritePrefix Perl module

%prep
%setup -q -n String-RewritePrefix-%{version}

%build
%{__perl} Makefile.PL INSTALLDIRS=vendor
make %{?_smp_mflags}

%install
rm -rf %{buildroot}

make pure_install PERL_INSTALL_ROOT=%{buildroot}

find %{buildroot} -type f -name .packlist -exec rm -f {} \;
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null \;

%{_fixperms} %{buildroot}/*

%check || :
make test

%clean
rm -rf %{buildroot}

%files
%defattr(-,root,root,-)
%doc Changes LICENSE META.json README dist.ini
%{perl_vendorlib}/*
%{_mandir}/man3/*

%changelog
* Thu Apr 04 2024 Otto J Wittner <otto.wittner@sikt.no> 0.009-1
- Specfile autogenerated by cpanspec 1.78.
