%{!?perl_vendorlib: %define perl_vendorlib %(eval "`%{__perl} -V:installvendorlib`"; echo $installvendorlib)}

Name:           perl-Graphics-Primitive-Driver-Cairo
Version:        0.47
Release:        1%{?dist}
Summary:        Cairo backend for Graphics::Primitive
License:        GPL+ or Artistic
Group:          Development/Libraries
URL:            http://search.cpan.org/dist/Graphics-Primitive-Driver-Cairo/
Source0:        Graphics-Primitive-Driver-Cairo-%{version}.tar.gz 
BuildRoot:      %{_tmppath}/%{name}-%{version}-%{release}-root-%(%{__id_u} -n)
BuildArch:      noarch
BuildRequires:  perl(Cairo)
BuildRequires:  perl(Carp)
BuildRequires:  perl(ExtUtils::MakeMaker)
BuildRequires:  perl(Geometry::Primitive::Point)
BuildRequires:  perl(Geometry::Primitive::Rectangle)
BuildRequires:  perl(Graphics::Color::RGB)
BuildRequires:  perl(Graphics::Primitive::Driver)
BuildRequires:  perl(Graphics::Primitive::Driver::TextLayout)
BuildRequires:  perl(Graphics::Primitive::Font)
BuildRequires:  perl(Graphics::Primitive::TextBox)
BuildRequires:  perl(IO::File)
BuildRequires:  perl(Math::Trig)
BuildRequires:  perl(Moose)
BuildRequires:  perl(Moose::Util::TypeConstraints)
BuildRequires:  perl(Test::More)
BuildRequires:  perl(Text::Flow)
BuildRequires:  perl(strict)
BuildRequires:  perl(warnings)
Requires:       perl(Cairo)
Requires:       perl(Carp)
Requires:       perl(Geometry::Primitive::Point)
Requires:       perl(Geometry::Primitive::Rectangle)
Requires:       perl(Graphics::Primitive::Driver)
Requires:       perl(Graphics::Primitive::Driver::TextLayout)
Requires:       perl(Graphics::Primitive::TextBox)
Requires:       perl(IO::File)
Requires:       perl(Math::Trig)
Requires:       perl(Moose)
Requires:       perl(Moose::Util::TypeConstraints)
Requires:       perl(Text::Flow)

Provides:       perl(Graphics::Primitive::Driver::Cairo)
Provides:       perl(Graphics::Primitive::Driver::Cairo::TextLayout)

%description
This module draws Graphics::Primitive objects using Cairo.

%prep
%setup -q -n Graphics-Primitive-Driver-Cairo-%{version}

%build
%{__perl} Makefile.PL INSTALLDIRS=vendor
make %{?_smp_mflags}

%install
rm -rf %{buildroot}

make pure_install PERL_INSTALL_ROOT=%{buildroot}

find %{buildroot} -type f -name .packlist -exec rm -f {} \;
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null \;

%{_fixperms} %{buildroot}/*

%check || :
make test

%clean
rm -rf %{buildroot}

%files
%defattr(-,root,root,-)
%doc Changes LICENSE META.json README README.mkdn
%{perl_vendorlib}/*
%{_mandir}/man3/*

%changelog
* Fri Apr 05 2024 Otto J Wittner <otto.wittner@sikt.no> 0.47-1
- Specfile autogenerated by cpanspec 1.78.
