#
# Logstash spec for incoming analytic results from Microdep scripts. 
# (Based very much on /etc/apache2/conf-available/apache-logstash.conf)
#
<IfModule proxy_module>
    ProxyRequests Off
    <Proxy *>
        <IfVersion >= 2.4>
            Require all granted
        </IfVersion>
        <IfVersion < 2.4>
            Order deny,allow
            Allow from all
        </IfVersion>
    </Proxy>

    ProxyPass /logstash-ana http://localhost:11285 status=+I
    ProxyPassReverse /logstash-ana http://localhost:11285 status=+I
    ProxyPreserveHost On

    <Location /logstash-ana>
        Authtype Basic
        Authname "Logstash-ana Pass"
        AuthUserFile /etc/perfsonar/opensearch/logstash_login
        <RequireAny>
           ##################
           ## Require a valid username and password
           Require valid-user

           ###################
           ## Enable IP based or hostname authentication as an alternative to username/pass
           ## The RequireAny means that as long as one of these match then writing will be allowed
           ## There are are many options, some of which are shown below but for full docs see
           ## https://httpd.apache.org/docs/2.4/howto/access.html
           ##
           ## Examples:
           ##
           ## Allow access from IPs 10.1.1.1 and 10.1.1.2
           ## or 2001:db8::a00:20ff:fea7:ccea
           ##
           ##
           # Require ip 10.1.1.1 10.1.1.2
           # Require ip 2001:db8::a00:20ff:fea7:ccea
           ##
           ## Allow access from subnet 10.1.1.0/24
           ## or subnet 2001:db8:2:1::/64
           ##
           # Require ip 10.1.1.0/24
           # Require ip 2001:db8:2:1::/64
           ##
           ## Allow access from a host named  example.perfsonar.net
           # Require host example.perfsonar.net
           ##
           ## Allow access from any host with a name ending in .edu or .gov
           ##
           # Require host gov edu
        </RequireAny>
    </Location>
</IfModule>
