%{!?perl_vendorlib: %define perl_vendorlib %(eval "`%{__perl} -V:installvendorlib`"; echo $installvendorlib)}

Name:           perl-Hash-Util-FieldHash-Compat
Version:        0.11
Release:        1%{?dist}
Summary:        Use Hash::Util::FieldHash or ties, depending on availability
License:        GPL+ or Artistic
Group:          Development/Libraries
URL:            http://search.cpan.org/dist/Hash-Util-FieldHash-Compat/
Source0:        Hash-Util-FieldHash-Compat-%{version}.tar.gz 
BuildRoot:      %{_tmppath}/%{name}-%{version}-%{release}-root-%(%{__id_u} -n)
BuildArch:      noarch
BuildRequires:  perl >= 0:5.006
BuildRequires:  perl(Exporter)
BuildRequires:  perl(ExtUtils::MakeMaker)
BuildRequires:  perl(File::Spec)
BuildRequires:  perl(Test::More) >= 0.88
BuildRequires:  perl(constant)
BuildRequires:  perl(parent)
BuildRequires:  perl(strict)
BuildRequires:  perl(warnings)
Requires:       perl(Exporter)
Requires:       perl(constant)
Requires:       perl(parent)
Requires:       perl(strict)
Requires:       perl(warnings)

Provides:       perl(Hash::Util::FieldHash::Compat)
Provides:       perl(Hash::Util::FieldHash::Compat::Heavy)

%description
Under older perls this module provides a drop-in compatible API to
Hash::Util::FieldHash using perltie. When Hash::Util::FieldHash is
available it will use that instead.

%prep
%setup -q -n Hash-Util-FieldHash-Compat-%{version}

%build
%{__perl} Makefile.PL INSTALLDIRS=vendor
make %{?_smp_mflags}

%install
rm -rf %{buildroot}

make pure_install PERL_INSTALL_ROOT=%{buildroot}

find %{buildroot} -type f -name .packlist -exec rm -f {} \;
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null \;

%{_fixperms} %{buildroot}/*

%check || :
make test

%clean
rm -rf %{buildroot}

%files
%defattr(-,root,root,-)
%doc CONTRIBUTING Changes LICENCE META.json README dist.ini
%{perl_vendorlib}/*
%{_mandir}/man3/*

%changelog
* Fri Apr 05 2024 Otto J Wittner <otto.wittner@sikt.no> 0.11-1
- Specfile autogenerated by cpanspec 1.78.
