%{!?perl_vendorlib: %define perl_vendorlib %(eval "`%{__perl} -V:installvendorlib`"; echo $installvendorlib)}

Name:           perl-Forest
Version:        0.10
Release:        1%{?dist}
Summary:        Collection of n-ary tree related modules
License:        GPL+ or Artistic
Group:          Development/Libraries
URL:            http://search.cpan.org/dist/Forest/
Source0:        Forest-%{version}.tar.gz 
BuildRoot:      %{_tmppath}/%{name}-%{version}-%{release}-root-%(%{__id_u} -n)
BuildArch:      noarch
BuildRequires:  perl(ExtUtils::MakeMaker)
BuildRequires:  perl(List::Util) >= 1.17
BuildRequires:  perl(Moose) >= 2.0000
BuildRequires:  perl(MooseX::Clone) >= 0.05
BuildRequires:  perl(Path::Class)
BuildRequires:  perl(Scalar::Util) >= 1.17
BuildRequires:  perl(Test::Exception)
BuildRequires:  perl(Test::More)
BuildRequires:  perl(inc::Module::Install)
Requires:       perl(List::Util) >= 1.17
Requires:       perl(Moose) >= 2.0000
Requires:       perl(MooseX::Clone) >= 0.05
Requires:       perl(Scalar::Util) >= 1.17

Provides:       perl(Forest)
Provides:       perl(Forest::Tree)
Provides:       perl(Forest::Tree::Builder)
Provides:       perl(Forest::Tree::Constructor)
Provides:       perl(Forest::Tree::Indexer)
Provides:       perl(Forest::Tree::Loader)
Provides:       perl(Forest::Tree::Pure)
Provides:       perl(Forest::Tree::Reader)
Provides:       perl(Forest::Tree::Writer)
Provides:       perl(Forest::Tree::Writer::ASCIIWithBranches)
Provides:       perl(Forest::Tree::Writer::SimpleASCII)
Provides:       perl(Forest::Tree::Writer::SimpleHTML)
Provides:       perl(Forest::Tree::Roles::HasNodeFormatter)
Provides:       perl(Forest::Tree::Roles::JSONable)
Provides:       perl(Forest::Tree::Roles::LoadWithMetaData)
Provides:       perl(Forest::Tree::Roles::MetaData)
Provides:       perl(Forest::Tree::Reader::SimpleTextFile)
Provides:       perl(Forest::Tree::Loader::SimpleUIDLoader)
Provides:       perl(Forest::Tree::Indexer::SimpleUIDIndexer)
Provides:       perl(Forest::Tree::Builder::Callback)
Provides:       perl(Forest::Tree::Builder::SimpleTextFile)

%description
Forest is intended to be a replacement for the Tree::Simple family of
modules, and fixes many of the issues that have always bothered me about
them. It is by no means a complete replacement yet, but should eventually
grow to become that.

%prep
%setup -q -n Forest-%{version}

%build
%{__perl} Makefile.PL INSTALLDIRS=vendor
make %{?_smp_mflags}

%install
rm -rf %{buildroot}

make pure_install PERL_INSTALL_ROOT=%{buildroot}

find %{buildroot} -type f -name .packlist -exec rm -f {} \;
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null \;

%{_fixperms} %{buildroot}/*

%check || :
make test

%clean
rm -rf %{buildroot}

%files
%defattr(-,root,root,-)
%doc Changes MYMETA.json MYMETA.yml README
%{perl_vendorlib}/*
%{_mandir}/man3/*

%changelog
* Fri Apr 05 2024 Otto J Wittner <otto.wittner@sikt.no> 0.10-1
- Specfile autogenerated by cpanspec 1.78.
