filter {
    # Fix issue with logstash-added hostname
    if [host] and ! [host][name] { mutate { rename => { "[host]" => "[host][name]" } } }

    # Add field for aggregation
    if [from] and [to] { mutate { add_field => { "[from_to]" => "%{[from]}_%{[to]}" } } }
}