%{!?perl_vendorlib: %define perl_vendorlib %(eval "`%{__perl} -V:installvendorlib`"; echo $installvendorlib)}

Name:           perl-Color-Library
Version:        0.021
Release:        1%{?dist}
Summary:        Easy-to-use and comprehensive named-color library
License:        GPL+ or Artistic
Group:          Development/Libraries
URL:            http://search.cpan.org/dist/Color-Library/
Source0:        Color-Library-%{version}.tar.gz 
BuildRoot:      %{_tmppath}/%{name}-%{version}-%{release}-root-%(%{__id_u} -n)
BuildArch:      noarch
BuildRequires:  perl(Class::Accessor::Fast)
BuildRequires:  perl(Class::Data::Inheritable)
BuildRequires:  perl(ExtUtils::MakeMaker)
BuildRequires:  perl(Module::Pluggable)
BuildRequires:  perl(Test::Most)
Requires:       perl(Class::Accessor::Fast)
Requires:       perl(Class::Data::Inheritable)
Requires:       perl(Module::Pluggable)

Provides:       perl(Color::Library)
Provides:       perl(Color::Library::Color)
Provides:       perl(Color::Library::Dictionary)
Provides:       perl(Color::Library::Dictionary::IE)
Provides:       perl(Color::Library::Dictionary::SVG)
Provides:       perl(Color::Library::Dictionary::WWW)
Provides:       perl(Color::Library::Dictionary::X11)
Provides:       perl(Color::Library::Dictionary::HTML)
Provides:       perl(Color::Library::Dictionary::Tango)
Provides:       perl(Color::Library::Dictionary::VACCC)
Provides:       perl(Color::Library::Dictionary::Mozilla)
Provides:       perl(Color::Library::Dictionary::Windows)
Provides:       perl(Color::Library::Dictionary::NBS_ISCC)
Provides:       perl(Color::Library::Dictionary::Netscape)
Provides:       perl(Color::Library::Dictionary::NBS_ISCC::A)
Provides:       perl(Color::Library::Dictionary::NBS_ISCC::B)
Provides:       perl(Color::Library::Dictionary::NBS_ISCC::F)
Provides:       perl(Color::Library::Dictionary::NBS_ISCC::H)
Provides:       perl(Color::Library::Dictionary::NBS_ISCC::M)
Provides:       perl(Color::Library::Dictionary::NBS_ISCC::P)
Provides:       perl(Color::Library::Dictionary::NBS_ISCC::R)
Provides:       perl(Color::Library::Dictionary::NBS_ISCC::S)
Provides:       perl(Color::Library::Dictionary::NBS_ISCC::RC)
Provides:       perl(Color::Library::Dictionary::NBS_ISCC::SC)
Provides:       perl(Color::Library::Dictionary::NBS_ISCC::TC)

%description
Color::Library is an easy-to-use and comprehensive named-color
dictionary. Currently provides coverage for www (svg, html, css) colors,
x11 colors, and more.

%prep
%setup -q -n Color-Library-%{version}

%build
%{__perl} Makefile.PL INSTALLDIRS=vendor
make %{?_smp_mflags}

%install
rm -rf %{buildroot}

make pure_install PERL_INSTALL_ROOT=%{buildroot}

find %{buildroot} -type f -name .packlist -exec rm -f {} \;
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null \;

%{_fixperms} %{buildroot}/*

%check || :
make test

%clean
rm -rf %{buildroot}

%files
%defattr(-,root,root,-)
%doc Changes README
%{perl_vendorlib}/*
%{_mandir}/man3/*

%changelog
* Fri Apr 05 2024 Otto J Wittner <otto.wittner@sikt.no> 0.021-1
- Specfile autogenerated by cpanspec 1.78.
