%{!?perl_vendorlib: %define perl_vendorlib %(eval "`%{__perl} -V:installvendorlib`"; echo $installvendorlib)}

Name:           perl-Graphics-Color
Version:        0.31
Release:        1%{?dist}
Summary:        Device and library agnostic color spaces
License:        GPL+ or Artistic
Group:          Development/Libraries
URL:            http://search.cpan.org/dist/Graphics-Color/
Source0:        Graphics-Color-%{version}.tar.gz 
BuildRoot:      %{_tmppath}/%{name}-%{version}-%{release}-root-%(%{__id_u} -n)
BuildArch:      noarch
BuildRequires:  perl(Color::Library)
BuildRequires:  perl(ExtUtils::MakeMaker)
BuildRequires:  perl(Moose)
BuildRequires:  perl(Moose::Role)
BuildRequires:  perl(Moose::Util::TypeConstraints)
BuildRequires:  perl(MooseX::Aliases) >= 0.10
BuildRequires:  perl(MooseX::Clone)
BuildRequires:  perl(MooseX::Storage::Deferred)
BuildRequires:  perl(MooseX::Types)
BuildRequires:  perl(MooseX::Types::Moose)
BuildRequires:  perl(Test::More)
BuildRequires:  perl(Test::Number::Delta)
BuildRequires:  perl(strict)
BuildRequires:  perl(warnings)
Requires:       perl(Color::Library)
Requires:       perl(Moose)
Requires:       perl(Moose::Role)
Requires:       perl(Moose::Util::TypeConstraints)
Requires:       perl(MooseX::Aliases) >= 0.10
Requires:       perl(MooseX::Clone)
Requires:       perl(MooseX::Storage::Deferred)
Requires:       perl(MooseX::Types)
Requires:       perl(MooseX::Types::Moose)

Provides:       perl(Graphics::Color)
Provides:       perl(Graphics::Color::HSL)
Provides:       perl(Graphics::Color::HSV)
Provides:       perl(Graphics::Color::RGB)
Provides:       perl(Graphics::Color::YIQ)
Provides:       perl(Graphics::Color::YUV)
Provides:       perl(Graphics::Color::CMYK)
Provides:       perl(Graphics::Color::Equal)
Provides:       perl(Graphics::Color::Types)

%description
Graphics color is a device and library agnostic system for creating and
manipulating colors in various color spaces.

%prep
%setup -q -n Graphics-Color-%{version}

%build
%{__perl} Makefile.PL INSTALLDIRS=vendor
make %{?_smp_mflags}

%install
rm -rf %{buildroot}

make pure_install PERL_INSTALL_ROOT=%{buildroot}

find %{buildroot} -type f -name .packlist -exec rm -f {} \;
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null \;

%{_fixperms} %{buildroot}/*

%check || :
make test

%clean
rm -rf %{buildroot}

%files
%defattr(-,root,root,-)
%doc Changes LICENSE META.json README README.mkdn
%{perl_vendorlib}/*
%{_mandir}/man3/*

%changelog
* Fri Apr 05 2024 Otto J Wittner <otto.wittner@sikt.no> 0.31-1
- Specfile autogenerated by cpanspec 1.78.
